version: '3'

services:
  db:
    image: postgres:latest
    command: postgres -c 'max_connections=200'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    restart: on-failure

  api:
    build:
      context: .
    command: >
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done;
      uvicorn asgi:fastapp --port 8000 --host 0.0.0.0 --reload'
    depends_on:
      - db
      - redis
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - .:/app/
    restart: on-failure

  nginx:
    command: nginx -g "daemon off;"
    depends_on:
      - api
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "0.0.0.0:8100:8000"

  worker:
    build:
      context: .
    command: >
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; 
      python3  ./worker/worker.py'
    volumes:
      - .:/app/
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - PYTHONPATH=/app
    depends_on:
      - api
      - db
      - redis
    restart: on-failure

  blocker:
    build:
      context: .
      dockerfile: blocker/Dockerfile
    command: python app.py
    depends_on:
      - redis
    volumes:
      - ./blocker/:/app/
    restart: always

  redis:
    image: redis
    restart: on-failure
    volumes:
        - ./redis/data:/data
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
        - 6379
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
      - URL_PREFIX=/redis_admin

volumes:
  postgresql-data:
  redis-data: