version: '3'

services:
  db:
    image: postgres:latest
    command: postgres -c 'max_connections=200'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    restart: on-failure

  api:
    build:
      context: .
    command: >
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done;
      uvicorn asgi:fastapp --port 8000 --host 0.0.0.0 --reload'
    depends_on:
      - db
    volumes:
      - .:/app/
    restart: on-failure

  nginx:
    command: nginx -g "daemon off;"
    depends_on:
      - api
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "127.0.0.1:8100:8000"

volumes:
  postgresql-data: